import os

# Import the environment from the calling build script
Import("environment turbojson")

# Create an array of source file names to compile
source = ["Lya.c", "Audio.c", "Map.c"]

# Determine which bufferfile implementation to use
l_env = environment.Clone()
configure = Configure(l_env)
if configure.CheckCHeader("sys/mman.h"):
    source.append("bufferfile_mmap.c")
elif configure.CheckCHeader("unistd.h") and configure.CheckCHeader("sys/stat.h"):
    source.append("bufferfile_unix.c")
else:
    source.append("bufferfile_c.c")
l_env = configure.Finish()

# Build a program using the environment. The first argument is the name of the program to build.
environment.Program("adventure", source, LIBS = ["SDL2", "SDL2_image", "m", "ogg", "opus", "openal", turbojson])
