# Import the environment from the calling build script
Import("environment")

# Create an array of source file names to compile
source = ["adventure.c"]

# Build a program using the environment. The first argument is the name of the program to build.
environment.Program("adventure", source, LIBS = ["sdl2"])
